name: S3 Deploy

on:
  workflow_call:
    inputs:
      AWS_S3_BUCKET:
        required: true
        type: string
      Artifactory_Name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifactory
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.Artifactory_Name }}
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to S3
        shell: bash
        run: ls -la
